import React, { useEffect, useState } from 'react';
import { CheckCircle2, Loader2, Search, ShieldCheck, UserRound, Wallet } from 'lucide-react';
import apiClient from '../../services/client';
import Modal from '../ui/Modal';
import Button from '../ui/Button';
import Input from '../ui/Input';
import Badge from '../ui/Badge';
import { useToast } from '../ui/Toast';
import { useLanguage } from '../../context/LanguageContext';
import { getInchillAdminDeviceId } from '../../utils/inchillDeviceId';

const EMPTY = { phone: '', countryCode: '', country: '', language: '' };
export default function InchillManagementModal({ provider, isOpen, onClose }) {
  const { addToast } = useToast(); const { dir } = useLanguage(); const id = provider?.id;
  const [connection, setConnection] = useState(null); const [form, setForm] = useState(EMPTY); const [otp, setOtp] = useState(''); const [busy, setBusy] = useState(false); const [diagnostics, setDiagnostics] = useState({}); const [targetId, setTargetId] = useState('');
  const refresh = async () => { if (!id) return; try { const data = await apiClient.suppliers.getInchillConnection(id); setConnection(data?.connection ?? null); } catch (error) { addToast(error?.message || 'Unable to load Inchill connection.', 'error'); } };
  useEffect(() => { if (isOpen) { setDiagnostics({}); setOtp(''); refresh(); } }, [isOpen, id]);
  const pending = connection?.pendingLogin; const connected = connection?.hasConnection === true; const run = async (task, key) => { setBusy(true); try { const result = await task(); if (key) setDiagnostics((old) => ({ ...old, [key]: result })); await refresh(); return result; } catch (error) { addToast(error?.message || 'Inchill request failed.', 'error'); } finally { setBusy(false); } };
  const sendOtp = (event) => { event.preventDefault(); run(() => apiClient.suppliers.sendInchillOtp(id, { phone: form.phone.trim(), countryCode: form.countryCode.trim(), deviceId: getInchillAdminDeviceId(), ...(form.country.trim() ? { country: form.country.trim().toUpperCase() } : {}), ...(form.language.trim() ? { language: form.language.trim() } : {}) })); };
  const verifyOtp = (event) => { event.preventDefault(); const submitted = otp.trim(); setOtp(''); if (submitted) run(() => apiClient.suppliers.verifyInchillOtp(id, submitted)); };
  if (!provider) return null;
  return <Modal isOpen={isOpen} onClose={onClose} title={`Inchill — ${provider.supplierName || provider.name || ''}`} size="xl"><div className="space-y-5" dir={dir}>
    <section className="rounded-2xl border border-[color:rgb(var(--color-primary-rgb)/0.24)] bg-[color:rgb(var(--color-primary-rgb)/0.07)] p-4">
      <div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.14em] text-[var(--color-primary)]">INCHILL CONNECTION</p><h4 className="mt-1 text-base font-bold text-gray-950 dark:text-white">Agent session</h4></div><Badge variant={connected ? 'success' : pending ? 'warning' : 'secondary'}>{connected ? 'CONNECTED' : pending ? 'OTP PENDING' : connection?.connectionStatus || 'UNKNOWN'}</Badge></div>
      {connected ? <div className="mt-4 flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={() => run(() => apiClient.suppliers.validateInchillSession(id))}><ShieldCheck className="h-4 w-4" />Validate session</Button></div> : null}
      {!pending ? <form onSubmit={sendOtp} className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><Input label="Agent phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required /><Input label="Country code" value={form.countryCode} onChange={(e) => setForm({ ...form, countryCode: e.target.value })} required /><Input label="Country (optional)" value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })} /><Input label="Language (optional)" value={form.language} onChange={(e) => setForm({ ...form, language: e.target.value })} /><Button type="submit" size="sm" disabled={busy}>{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : null}Send OTP</Button></form> : <form onSubmit={verifyOtp} className="mt-4 flex gap-2"><Input label="OTP" value={otp} onChange={(e) => setOtp(e.target.value)} inputMode="numeric" required /><Button type="submit" size="sm" disabled={busy || !otp.trim()}><CheckCircle2 className="h-4 w-4" />Verify OTP</Button></form>}
    </section>
    <section className="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900/40"><p className="text-xs font-semibold tracking-[0.14em] text-[var(--color-primary)]">READ-ONLY DIAGNOSTICS</p><div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-3"><Button size="sm" variant="outline" disabled={!connected || busy} onClick={() => run(() => apiClient.suppliers.getInchillProfile(id), 'profile')}><UserRound className="h-4 w-4" />Profile</Button><Button size="sm" variant="outline" disabled={!connected || busy} onClick={() => run(() => apiClient.suppliers.getInchillWallet(id), 'wallet')}><Wallet className="h-4 w-4" />Diamond balance</Button><Button size="sm" variant="outline" disabled={!connected || busy} onClick={() => run(() => apiClient.suppliers.getInchillReadiness(id), 'readiness')}><ShieldCheck className="h-4 w-4" />Readiness</Button></div>{diagnostics.profile?.profile ? <p className="mt-3 text-sm">{diagnostics.profile.profile.nickName || diagnostics.profile.profile.vid || 'Agent profile loaded'}</p> : null}{diagnostics.wallet?.wallet ? <p className="mt-2 text-sm">Diamond: {diagnostics.wallet.wallet.diamond ?? '—'}</p> : null}<form onSubmit={(e) => { e.preventDefault(); if (targetId.trim()) run(() => apiClient.suppliers.verifyInchillTarget(id, targetId.trim()), 'target'); }} className="mt-4 flex gap-2"><Input value={targetId} onChange={(e) => setTargetId(e.target.value)} placeholder="Target ID" disabled={!connected} /><Button type="submit" size="sm" disabled={!connected || busy || !targetId.trim()}><Search className="h-4 w-4" />Verify</Button></form>{diagnostics.target?.verification ? <p className="mt-2 text-sm">{diagnostics.target.verification.nickName || diagnostics.target.verification.vid}</p> : null}</section>
  </div></Modal>;
}
